# Generated by Django 2.2.8 on 2022-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=55, unique=True)),
                ('images1', models.ImageField(null=True, upload_to='images/images')),
                ('images2', models.ImageField(null=True, upload_to='images/images')),
                ('images3', models.ImageField(null=True, upload_to='images/images')),
                ('images4', models.ImageField(null=True, upload_to='images/images')),
            ],
        ),
    ]
