# Generated by Django 2.2.8 on 2022-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_categoriesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimg',
            name='images1',
        ),
        migrations.RemoveField(
            model_name='galleryimg',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='galleryimg',
            name='images3',
        ),
        migrations.RemoveField(
            model_name='galleryimg',
            name='images4',
        ),
        migrations.AddField(
            model_name='galleryimg',
            name='caption',
            field=models.TextField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimg',
            name='image',
            field=models.ImageField(null=True, upload_to='image/image'),
        ),
        migrations.AlterField(
            model_name='galleryimg',
            name='username',
            field=models.TextField(max_length=55),
        ),
    ]
