# Generated by Django 2.2.8 on 2022-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
                ('username', models.TextField(max_length=100)),
                ('product_id', models.TextField()),
                ('product_name', models.TextField(max_length=100)),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
                ('image', models.TextField(max_length=100)),
            ],
        ),
    ]
